import {GLASS_VERT,GLASS_FRAG} from './glass-v4-shader.js';

export function createLumaGlass({$, $$, state, getSlideFrame}){
 const canvas=$('#glassCanvas');let gl,program,texture,backdrop,ctx;let viewerMode=false,currentSlideImg=null,theme='light',running=false,geometryDirty=true,backdropDirty=true,lastTs=0,dpr=1;const loc={},pressMap=new WeakMap();
 const mobile=matchMedia('(max-width:760px)').matches,memory=Number(navigator.deviceMemory||4),cores=Number(navigator.hardwareConcurrency||4);const tier=(!mobile&&memory>=8&&cores>=8)?2:((memory<=3||cores<=4)?0:1),MAX=tier===2?16:(tier===1?12:8),modeCode={regular:0,clear:1,interactive:2,thick:3};let shapes=[];
 const shapeBuf=new Float32Array(64),radiusBuf=new Float32Array(16),pressBuf=new Float32Array(16),pressPointBuf=new Float32Array(32),modeBuf=new Float32Array(16);
 function compile(type,src){const sh=gl.createShader(type);gl.shaderSource(sh,src);gl.compileShader(sh);if(!gl.getShaderParameter(sh,gl.COMPILE_STATUS))throw new Error(gl.getShaderInfoLog(sh)||'shader compile failed');return sh;}
 function init(){try{gl=canvas.getContext('webgl2',{alpha:true,premultipliedAlpha:false,antialias:tier>0,preserveDrawingBuffer:false});if(!gl)throw new Error('WebGL2 unavailable');program=gl.createProgram();gl.attachShader(program,compile(gl.VERTEX_SHADER,GLASS_VERT));gl.attachShader(program,compile(gl.FRAGMENT_SHADER,GLASS_FRAG));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw new Error(gl.getProgramInfoLog(program)||'shader link failed');gl.useProgram(program);const quad=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,quad);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,1,-1,-1,1,-1,1,1,-1,1,1]),gl.STATIC_DRAW);const aPos=gl.getAttribLocation(program,'aPos');gl.enableVertexAttribArray(aPos);gl.vertexAttribPointer(aPos,2,gl.FLOAT,false,0,0);texture=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,texture);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);for(const n of ['uResolution','uDpr','uTier','uDark','uViewer','uCount','uBackdrop'])loc[n]=gl.getUniformLocation(program,n);loc.shape=gl.getUniformLocation(program,'uShape[0]');loc.radius=gl.getUniformLocation(program,'uRadius[0]');loc.press=gl.getUniformLocation(program,'uPress[0]');loc.pressPoint=gl.getUniformLocation(program,'uPressPoint[0]');loc.mode=gl.getUniformLocation(program,'uMode[0]');backdrop=document.createElement('canvas');ctx=backdrop.getContext('2d',{alpha:false});resize();bindInteractions();window.addEventListener('resize',resize,{passive:true});window.addEventListener('scroll',()=>{geometryDirty=true;},{passive:true});new ResizeObserver(()=>{geometryDirty=true;}).observe(document.documentElement);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&!running){running=true;lastTs=0;requestAnimationFrame(frame);}});running=true;requestAnimationFrame(frame);}catch(err){console.warn('LumaGlass fallback',err);document.documentElement.classList.add('no-webgl');canvas.style.display='none';}}
 function bindInteractions(){$$('[data-glass]').forEach(el=>{if(el.dataset.glassBound)return;el.dataset.glassBound='1';el.addEventListener('pointerdown',e=>press(el,true,e));el.addEventListener('pointermove',e=>{const p=pressMap.get(el);if(p?.target>0)updatePressPoint(el,e,p);});el.addEventListener('pointerup',e=>press(el,false,e));el.addEventListener('pointercancel',e=>press(el,false,e));});}
 function updatePressPoint(el,e,p){const r=el.getBoundingClientRect();p.x=Math.max(0,Math.min(r.width,e.clientX-r.left));p.y=Math.max(0,Math.min(r.height,e.clientY-r.top));geometryDirty=true;}
 function resize(){if(!gl)return;const cap=tier===2?1.75:(tier===1?1.5:1);dpr=Math.min(window.devicePixelRatio||1,cap);const w=Math.max(1,Math.min(innerWidth,560)),h=Math.max(1,innerHeight);canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);backdrop.width=canvas.width;backdrop.height=canvas.height;canvas.style.width=w+'px';canvas.style.height=h+'px';gl.viewport(0,0,canvas.width,canvas.height);geometryDirty=true;backdropDirty=true;}
 function refreshShapes(){geometryDirty=true;bindInteractions();}
 function updateGeometry(){if(!gl)return;const cr=canvas.getBoundingClientRect(),sx=canvas.width/Math.max(1,cr.width),sy=canvas.height/Math.max(1,cr.height);const els=$$('[data-glass]'),rects=els.map(el=>[el,el.getBoundingClientRect(),getComputedStyle(el)]);shapes=rects.filter(([,r,st])=>st.display!=='none'&&st.visibility!=='hidden'&&Number(st.opacity)!==0&&r.width>2&&r.height>2&&r.bottom>0&&r.top<innerHeight).slice(0,MAX).map(([el,r])=>{const rad=parseFloat(el.dataset.radius||'24');let p=pressMap.get(el);if(!p){p={value:0,target:0,v:0,x:r.width/2,y:r.height/2};pressMap.set(el,p);}return{el,cx:(r.left+r.width/2-cr.left)*sx,cy:(cr.height-(r.top+r.height/2-cr.top))*sy,hw:r.width/2*sx,hh:r.height/2*sy,r:rad*((sx+sy)/2),p,px:(r.left+p.x-cr.left)*sx,py:(cr.height-(r.top+p.y-cr.top))*sy,mode:modeCode[el.dataset.glass]??0};});geometryDirty=false;}
 function rr(x,y,w,h,r,fill){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fillStyle=fill;ctx.fill();}
 function drawBackdrop(){if(!ctx)return;const w=backdrop.width,h=backdrop.height,dark=theme==='dark';ctx.clearRect(0,0,w,h);const g=ctx.createLinearGradient(0,0,0,h);if(viewerMode){if(dark){g.addColorStop(0,'#101713');g.addColorStop(1,'#050806');}else{g.addColorStop(0,'#f7fbf8');g.addColorStop(.55,'#eef5f0');g.addColorStop(1,'#e5eee8');}}else if(dark){g.addColorStop(0,'#0a120f');g.addColorStop(.52,'#111b16');g.addColorStop(1,'#09100d');}else{g.addColorStop(0,'#f8faf6');g.addColorStop(.53,'#eef3ed');g.addColorStop(1,'#e7eee8');}ctx.fillStyle=g;ctx.fillRect(0,0,w,h);
  if(viewerMode){const cr=canvas.getBoundingClientRect(),r=getSlideFrame?.()?.getBoundingClientRect?.();if(r&&currentSlideImg?.complete&&currentSlideImg.naturalWidth&&/^(data:|blob:)/.test(currentSlideImg.src)){try{ctx.globalAlpha=dark?.24:.16;ctx.drawImage(currentSlideImg,(r.left-cr.left)*dpr,(r.top-cr.top)*dpr,r.width*dpr,r.height*dpr);ctx.globalAlpha=1;}catch{}}const rg=ctx.createRadialGradient(w*.5,h*.28,0,w*.5,h*.28,w*.55);rg.addColorStop(0,dark?'rgba(72,173,137,.20)':'rgba(74,199,154,.17)');rg.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=rg;ctx.fillRect(0,0,w,h);backdropDirty=false;return;}
  ctx.save();ctx.globalAlpha=dark?.065:.055;ctx.strokeStyle=dark?'#d8f7ea':'#174a37';ctx.lineWidth=Math.max(1,dpr*.65);const grid=42*dpr;for(let x=0;x<w;x+=grid){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke();}for(let y=0;y<h;y+=grid){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke();}ctx.restore();
  const fields=dark?[[w*.92,h*.08,w*.42,'rgba(83,220,174,.18)'],[w*.03,h*.58,w*.36,'rgba(177,136,234,.10)'],[w*.98,h*.84,w*.30,'rgba(235,173,103,.08)']]:[[w*.92,h*.08,w*.46,'rgba(96,225,181,.40)'],[w*.02,h*.58,w*.40,'rgba(190,162,237,.20)'],[w*.98,h*.84,w*.33,'rgba(244,194,129,.17)']];for(const[x,y,r,c]of fields){const rg=ctx.createRadialGradient(x,y,0,x,y,r);rg.addColorStop(0,c);rg.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=rg;ctx.fillRect(0,0,w,h);}
  const cards=[{x:-.10,y:.13,w:.54,h:.16,rot:-.09,a:dark?'rgba(27,67,53,.48)':'rgba(205,239,227,.72)',accent:'#25a77f',label:'STORY',title:'IDEA → CLARITY'},{x:.68,y:.25,w:.52,h:.16,rot:.08,a:dark?'rgba(65,48,91,.38)':'rgba(226,214,248,.66)',accent:'#9275c8',label:'VISUAL',title:'FOCUS / FLOW'},{x:-.18,y:.73,w:.54,h:.15,rot:.07,a:dark?'rgba(83,57,29,.30)':'rgba(248,224,185,.56)',accent:'#c48b45',label:'10 SLIDES',title:'BUILT TO LAND'}];for(const c of cards){ctx.save();const cx=c.x*w,cy=c.y*h,cw=c.w*w,ch=c.h*w;ctx.translate(cx+cw/2,cy+ch/2);ctx.rotate(c.rot);rr(-cw/2,-ch/2,cw,ch,28*dpr,c.a);ctx.globalAlpha=dark?.58:.72;ctx.fillStyle=dark?'#eaf8f1':'#163c30';ctx.font=`800 ${Math.round(7.5*dpr)}px sans-serif`;ctx.fillText(c.label,-cw*.38,-ch*.08);ctx.font=`800 ${Math.round(12*dpr)}px sans-serif`;ctx.fillText(c.title,-cw*.38,ch*.16);rr(-cw*.38,ch*.28,cw*.28,3*dpr,3*dpr,c.accent);ctx.restore();ctx.globalAlpha=1;}
  ctx.save();ctx.globalAlpha=dark?.12:.15;ctx.strokeStyle=dark?'#bfe9da':'#0b7358';ctx.lineWidth=Math.max(1,dpr*.7);ctx.beginPath();ctx.moveTo(w*.07,h*.105);ctx.lineTo(w*.93,h*.105);ctx.stroke();ctx.beginPath();ctx.arc(w*.83,h*.37,w*.17,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.arc(w*.83,h*.37,w*.095,0,Math.PI*2);ctx.stroke();ctx.fillStyle=dark?'#e5f8f0':'#173d31';ctx.font=`800 ${Math.round(8*dpr)}px sans-serif`;ctx.fillText('LUMADECK  /  CREATE  /  PRESENT',w*.07,h*.075);ctx.globalAlpha=dark?.06:.075;ctx.font=`900 ${Math.round(30*dpr)}px sans-serif`;ctx.fillText('BUILD',w*.58,h*.445);ctx.restore();backdropDirty=false;}
 function uploadBackdrop(){if(!backdropDirty)return;drawBackdrop();gl.bindTexture(gl.TEXTURE_2D,texture);gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL,false);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,backdrop);}
 function stepSprings(dt){for(const s of shapes){const p=s.p,stiffness=state.reduceMotion?900:420,damping=state.reduceMotion?60:27,acc=(p.target-p.value)*stiffness-p.v*damping;p.v+=acc*dt;p.value+=p.v*dt;}}
 function frame(ts){if(document.visibilityState==='hidden'){running=false;return;}const minFrame=tier===0?33:16;if(ts-lastTs<minFrame){requestAnimationFrame(frame);return;}const dt=Math.min(.034,lastTs?(ts-lastTs)/1000:1/60);lastTs=ts;if(geometryDirty)updateGeometry();stepSprings(dt);uploadBackdrop();shapeBuf.fill(0);radiusBuf.fill(0);pressBuf.fill(0);pressPointBuf.fill(0);modeBuf.fill(0);shapes.forEach((s,i)=>{shapeBuf.set([s.cx,s.cy,s.hw,s.hh],i*4);radiusBuf[i]=s.r;pressBuf[i]=Math.max(0,Math.min(1.2,s.p.value));pressPointBuf.set([s.px,s.py],i*2);modeBuf[i]=s.mode;});gl.useProgram(program);gl.uniform1i(loc.uBackdrop,0);gl.uniform2f(loc.uResolution,canvas.width,canvas.height);gl.uniform1f(loc.uDpr,dpr);gl.uniform1f(loc.uTier,tier);gl.uniform1f(loc.uDark,theme==='dark'?1:0);gl.uniform1f(loc.uViewer,viewerMode?1:0);gl.uniform1i(loc.uCount,shapes.length);gl.uniform4fv(loc.shape,shapeBuf);gl.uniform1fv(loc.radius,radiusBuf);gl.uniform1fv(loc.press,pressBuf);gl.uniform2fv(loc.pressPoint,pressPointBuf);gl.uniform1fv(loc.mode,modeBuf);gl.clearColor(0,0,0,0);gl.clear(gl.COLOR_BUFFER_BIT);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);gl.drawArrays(gl.TRIANGLES,0,6);requestAnimationFrame(frame);}
 function press(el,on,e){const r=el.getBoundingClientRect();let p=pressMap.get(el);if(!p){p={value:0,target:0,v:0,x:r.width/2,y:r.height/2};pressMap.set(el,p);}p.target=on?1:0;if(e)updatePressPoint(el,e,p);geometryDirty=true;}
 function setViewer(v){viewerMode=!!v;geometryDirty=true;backdropDirty=true;}
 function setSlide(url){currentSlideImg=new Image();currentSlideImg.onload=()=>{backdropDirty=true;};currentSlideImg.onerror=()=>{currentSlideImg=null;backdropDirty=true;};if(!/^(data:|blob:)/.test(url||''))currentSlideImg.crossOrigin='anonymous';currentSlideImg.src=url||'';}
 function setTheme(t){theme=t;backdropDirty=true;}
 function markBackdrop(){backdropDirty=true;}
 return{init,refreshShapes,press,setViewer,setSlide,setTheme,markBackdrop,tier};
}
