const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const list=$('#historyList'),count=$('#historyCount'),viewer=$('#viewer'),viewerTitle=$('#viewerTitle');
let jobs=[],nodeById=new Map(),busy=false,timer=null,switchSig='';
const css=`
.project-card{width:100%;border:0;border-bottom:1px solid var(--hair);background:transparent;color:var(--ink);padding:15px 2px 14px;text-align:left;display:grid;grid-template-columns:46px 1fr auto;gap:11px;align-items:center}.project-card:active{transform:scale(.992)}
.project-mark{width:44px;height:44px;border-radius:17px;background:linear-gradient(145deg,var(--accent),var(--accent-deep));color:#fff;display:grid;place-items:center;font-family:'Manrope',sans-serif;font-size:13px;font-weight:900;box-shadow:0 10px 24px color-mix(in srgb,var(--accent) 23%,transparent)}
.project-copy{min-width:0}.project-copy>b{display:block;font-family:'Manrope',sans-serif;font-size:13px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.project-copy>small{display:block;color:var(--muted);font-size:9px;margin-top:4px}.variant-chips{display:flex;gap:5px;flex-wrap:wrap;margin-top:8px}.variant-chip{height:25px;padding:0 9px;border-radius:12px;border:1px solid var(--hair);background:color-mix(in srgb,var(--surface-2) 84%,transparent);display:inline-flex;align-items:center;gap:5px;font-size:8px;font-weight:900;color:var(--muted)}.variant-chip i{width:5px;height:5px;border-radius:50%;background:var(--muted);opacity:.45}.variant-chip.ready{color:var(--accent);border-color:color-mix(in srgb,var(--accent) 25%,var(--hair));background:color-mix(in srgb,var(--mint) 60%,var(--surface-2))}.variant-chip.ready i{background:var(--accent);opacity:1}.project-chevron{font-size:22px;color:var(--muted)}
.variant-switch{display:flex;gap:6px;padding:3px 4px 7px;overflow-x:auto;scrollbar-width:none}.variant-switch::-webkit-scrollbar{display:none}.variant-tab{flex:0 0 auto;height:32px;padding:0 13px;border-radius:16px;border:1px solid rgba(255,255,255,.13);background:rgba(255,255,255,.07);color:rgba(255,255,255,.68);font-size:9px;font-weight:900;letter-spacing:.02em;display:flex;align-items:center;gap:6px}.variant-tab i{width:5px;height:5px;border-radius:50%;background:rgba(255,255,255,.35)}.variant-tab.active{background:rgba(101,218,180,.20);border-color:rgba(101,218,180,.38);color:#fff}.variant-tab.active i{background:#65dab4;box-shadow:0 0 0 4px rgba(101,218,180,.10)}
`;
const style=document.createElement('style');style.textContent=css;document.head.appendChild(style);
function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function commonTitle(arr){const titles=arr.map(x=>x.title||x.promptPreview||'Presentation');if(titles.length===1)return titles[0];let p=titles[0];for(const t of titles.slice(1)){let i=0;while(i<p.length&&i<t.length&&p[i]===t[i])i++;p=p.slice(0,i);}p=p.replace(/[\s·—–|:,-]+$/,'').trim();return p.length>=8?p:titles[0].replace(/\s*[—–-]\s*(Variant|V)\s*\d+.*$/i,'');}
function groupJobs(){const m=new Map();for(const j of jobs){const k=j.projectGroupId||j.id;if(!m.has(k))m.set(k,[]);m.get(k).push(j);}return [...m.values()].map(g=>g.sort((a,b)=>(a.variantIndex||1)-(b.variantIndex||1))).sort((a,b)=>Math.max(...b.map(x=>Number(x.createdAt)||0))-Math.max(...a.map(x=>Number(x.createdAt)||0)));}
function preferred(g){return [...g].reverse().find(j=>j.status==='ready'&&j.previewUrls?.length)||[...g].reverse()[0];}
function clickJob(j){const n=nodeById.get(j.id);if(n){n.click();return true;}return false;}
async function fetchJobs(){try{const r=await fetch('/api/jobs',{credentials:'include'});if(!r.ok)return false;const d=await r.json();jobs=d.jobs||[];return true;}catch{return false;}}
async function enhance(){if(busy||!list)return;const original=$$('.job-card',list);if(!original.length)return;busy=true;try{if(!await fetchJobs())return;nodeById=new Map();jobs.forEach((j,i)=>{if(original[i])nodeById.set(j.id,original[i]);});const groups=groupJobs();list.innerHTML='';for(const g of groups){const top=preferred(g),ready=g.filter(x=>x.status==='ready').length,b=document.createElement('button');b.className='project-card';b.innerHTML=`<span class="project-mark">${g.length>1?'2V':'1V'}</span><span class="project-copy"><b>${esc(commonTitle(g))}</b><small>${g.length>1?`${g.length} variants · ${ready}/${g.length} ready`:`${top.status==='ready'?'Ready':`${top.progress||0}%`} · ${(top.outputFormat||'pptx').toUpperCase()}`}</small><span class="variant-chips">${g.map(v=>`<span class="variant-chip ${v.status==='ready'?'ready':''}"><i></i>${esc(v.variantLabel||`Variant ${v.variantIndex||1}`)}</span>`).join('')}</span></span><span class="project-chevron">›</span>`;b.addEventListener('click',()=>clickJob(top));list.appendChild(b);}if(count)count.textContent=String(groups.length);refreshVariantSwitch();}finally{busy=false;}}
function selectedJob(){const t=viewerTitle?.textContent?.trim();if(!t)return null;return jobs.find(j=>(j.title||'').trim()===t)||null;}
function refreshVariantSwitch(){if(!viewer?.classList.contains('open')){$('.variant-switch')?.remove();switchSig='';return;}const sel=selectedJob();if(!sel)return;const gid=sel.projectGroupId||sel.id,g=jobs.filter(j=>(j.projectGroupId||j.id)===gid).sort((a,b)=>(a.variantIndex||1)-(b.variantIndex||1));let bar=$('.variant-switch',viewer);if(g.length<2){bar?.remove();switchSig='';return;}if(!bar){bar=document.createElement('div');bar.className='variant-switch';$('.viewer-title-row',viewer)?.after(bar);}const sig=`${sel.id}|${g.map(v=>`${v.id}:${v.status}`).join('|')}`;if(sig===switchSig)return;switchSig=sig;bar.innerHTML=g.map(v=>`<button class="variant-tab ${v.id===sel.id?'active':''}" data-id="${v.id}"><i></i>${esc(v.variantLabel||`Variant ${v.variantIndex||1}`)}</button>`).join('');$$('.variant-tab',bar).forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();const j=jobs.find(x=>x.id===b.dataset.id);if(j?.status==='ready')clickJob(j);}));}
const mo=new MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(()=>{if(!busy)enhance();refreshVariantSwitch();},80);});if(list)mo.observe(list,{childList:true,subtree:false});if(viewer)mo.observe(viewer,{attributes:true,attributeFilter:['class'],subtree:true,childList:true,characterData:true});setTimeout(enhance,450);setInterval(()=>{if(!busy&&viewer?.classList.contains('open'))refreshVariantSwitch();},900);
